# Generated by Django 3.2 on 2022-09-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=256)),
                ('start_mailing', models.DateTimeField()),
                ('stop_mailing', models.DateTimeField()),
                ('tag', models.CharField(max_length=64, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('mailing_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_list.mailinglist')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing_list.messagestatus')),
            ],
        ),
    ]
